apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-persistent-volumes.yaml
  - 01-configmaps.yaml
  - 02-sqlserver.yaml
  - 03-mongodb.yaml
  - 04-rabbitmq.yaml
  - 05-api.yaml
  - 06-worker.yaml
  - 07-observability-configmaps.yaml
  - 08-prometheus.yaml
  - 09-grafana.yaml
  - 10-zabbix.yaml
  - 11-blackbox-exporter.yaml
  - 12-frontend.yaml
